import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {Store} from '../store.js';
import {Queue} from '../queue.js';
import {ApplicationControl,requestCapability} from '../application-control.js';
import {Telegram} from '../telegram.js';
const since='2026-10-10T12:00:00.000Z',at='2026-10-10T12:10:00.000Z',date=Date.parse('2026-10-10T12:01:00Z')/1000;
function fixture(dir=mkdtempSync(join(tmpdir(),'delayed-ingress-')),disk=false){const s=new Store(disk?join(dir,'operational.sqlite'):':memory:'),q=new Queue(s),c=new ApplicationControl(s,q),calls:string[]=[],t=new Telegram(s,c,dir,{call:async(method)=>{calls.push(method);return {message_id:1};}});if(!s.get('telegramBinding')){s.set('telegramConfigured',true);s.set('telegramBotGeneration','bot-A');s.set('telegramBinding',{generation:'binding-A',userId:42,chatId:42,since});s.set('enabled',false);}return {dir,s,q,c,t,calls,close(remove=true){t.stop();s.close();if(remove)rmSync(dir,{recursive:true,force:true});}};}
const update=(id:number,text:string,time=date)=>({update_id:id,message:{date:time,text,from:{id:42},chat:{id:42,type:'private'}}});
function ignored(f:ReturnType<typeof fixture>,id:number,text:string,legacy=true){f.t.ingest([update(id,text)]);if(legacy){const row=f.s.one('SELECT body FROM telegram_updates WHERE update_id=?',id),body=JSON.parse(row.body);delete body.botGeneration;f.s.run('UPDATE telegram_updates SET body=? WHERE update_id=?',JSON.stringify(body),id);}f.s.run("UPDATE telegram_updates SET status='ignored',error='Stale incoming command' WHERE update_id=?",id);return f.s.one('SELECT * FROM telegram_updates WHERE update_id=?',id);}
const jobs=(f:ReturnType<typeof fixture>)=>f.s.all('SELECT * FROM jobs');
const noEffects=(f:ReturnType<typeof fixture>)=>{assert.equal(f.s.all('SELECT * FROM operations').length,0);assert.equal(f.s.all('SELECT * FROM ledger').length,0);assert.equal(f.s.all('SELECT * FROM owner_proposals').length,0);assert.equal(f.s.get('enabled'),false);};
test('delayed current-bound chat and four harmless commands survive durable cursor/reopen without expanding capability',async()=>{const dir=mkdtempSync(join(tmpdir(),'delayed-live-'));let f=fixture(dir,true);try{f.t.ingest([update(100,'Ci sei?'),...['/status','/help','/queue','/menu'].map((text,i)=>update(101+i,text))]);assert.equal(f.s.get('telegramCursor'),105);f.close(false);f=fixture(dir,true);await f.t.process(at);assert.equal(jobs(f).length,1);assert.equal(f.s.get('jobCapability:'+jobs(f)[0].id),'read_only_chat');assert.equal(jobs(f)[0].request_id,'telegram:bot-A:100');assert.equal(jobs(f)[0].state,'queued');assert.equal(f.s.all("SELECT * FROM telegram_updates WHERE status='done'").length,5);assert.equal(f.s.all('SELECT * FROM telegram_outbox').length,5);await f.t.process(at);assert.equal(jobs(f).length,1);noEffects(f);}finally{f.close();}});
test('legacy ignored read-only rows recover additively under original IDs and preserve original ignored receipt bytes',async()=>{const f=fixture();try{const original=ignored(f,100,'Spiega lo stato del nodo'),status=ignored(f,101,'/status');await f.t.process(at);assert.deepEqual(f.s.one('SELECT * FROM telegram_updates WHERE update_id=100'),original);assert.deepEqual(f.s.one('SELECT * FROM telegram_updates WHERE update_id=101'),status);const snapshot=f.s.get('telegramIngressRecoveryOriginal:100');assert.deepEqual(snapshot,{updateId:100,body:original.body,status:'ignored',error:'Stale incoming command'});assert.equal(f.s.get('telegramIngressRecovery:100').state,'done');assert.equal(jobs(f)[0].request_id,'telegram:bot-A:100');assert.equal(f.s.one("SELECT count(*) n FROM telegram_outbox WHERE event_id='update:100'").n,1);f.t.ingest([update(100,'different later body')]);await f.t.process(at);assert.equal(jobs(f).length,1);assert.deepEqual(f.s.get('telegramIngressRecoveryOriginal:100'),snapshot);assert.deepEqual(f.s.one('SELECT * FROM telegram_updates WHERE update_id=100'),original);noEffects(f);}finally{f.close();}});
test('shared classifier preserves all original source/purpose/analysis/manual-proposal priorities',()=>{const f=fixture();try{for(const source of ['owner','telegram'] as const)for(const analysis of [false,true])for(const purpose of [undefined,'general','economic','qualification'] as const)for(const message of ['Ci sei?','proponimi una fee','APPROVA','review pricing','valuta prima di agire','conferma']){const review=/\b(approv|review|propos|propon|valut.*prima|conferm)/i.test(message),expected=purpose==='qualification'?'read_only_qualification':analysis?'read_only_research':review?'guarded_manual_proposal':source==='telegram'?'read_only_chat':'financial_guarded',id='invariant:'+source+analysis+purpose+message;assert.equal(requestCapability(message,source,analysis,purpose),expected);const job=f.c.admit(id,message,source,analysis,purpose);assert.equal(f.s.get('jobCapability:'+job.id),expected);}noEffects(f);}finally{f.close();}});
test('expired stateful/analysis/proposal commands retain expiry and ignored callbacks/pairing/Stop never recover',async()=>{const f=fixture();try{const texts=['/pause','/resume','/stop','/analyze','/analyze approfondisci','/proposals','/unknown','proponimi una fee','approva questo','valuta prima'];f.t.ingest(texts.map((text,i)=>update(100+i,text)));await f.t.process(at);assert.equal(jobs(f).length,0);assert.equal(f.s.all('SELECT * FROM telegram_outbox').length,0);assert.ok(f.s.all('SELECT * FROM telegram_updates').every(r=>r.status==='ignored'));const callback={generation:'binding-A',chatId:42,chatType:'private',userId:42,text:'/status',date,callbackId:'old',callback:'old-key'};for(const [i,body] of [callback,{...callback,callbackId:undefined,callback:'',stoppedDraft:7},{...callback,callbackId:undefined,callback:'',text:'/start',codeDigest:'expired'}].entries())f.s.run("INSERT INTO telegram_updates(update_id,body,status,error) VALUES(?,?,'ignored','Stale incoming command')",200+i,JSON.stringify(body));await f.t.process(at);assert.equal(jobs(f).length,0);assert.equal(f.calls.length,0);assert.equal(f.s.all("SELECT * FROM meta WHERE key LIKE 'telegramIngressRecovery:%'").length,0);noEffects(f);}finally{f.close();}});
test('read-only eligibility does not weaken before-binding/future/malformed timestamps or foreign binding/bot guards',async()=>{const f=fixture();try{f.t.ingest([update(100,'Ci sei?',Date.parse(since)/1000-1),update(101,'/status',Date.parse(at)/1000+61),update(102,'/help',NaN),update(103,'Spiega lo stato')]);const row=f.s.one('SELECT body FROM telegram_updates WHERE update_id=103'),body=JSON.parse(row.body);body.botGeneration='old-bot';f.s.run('UPDATE telegram_updates SET body=? WHERE update_id=103',JSON.stringify(body));await f.t.process(at);await f.t.process(at);assert.equal(jobs(f).length,0);assert.equal(f.s.all('SELECT * FROM telegram_outbox').length,0);noEffects(f);}finally{f.close();}});
test('re-pair and replacement bot cannot recover retained legacy/current-bound records from old authority',async()=>{for(const transition of ['pair','bot']){const f=fixture();try{const original=ignored(f,100,'Spiega lo stato',transition==='pair');if(transition==='pair'){f.t.revoke();f.s.set('telegramCandidate',{userId:42,chatId:42,expires:'2026-10-10T12:20:00Z'});f.t.confirm(42,at);}else f.s.set('telegramBotGeneration','bot-B');await f.t.process(at);assert.equal(jobs(f).length,0);assert.deepEqual(f.s.one('SELECT * FROM telegram_updates WHERE update_id=100'),original);noEffects(f);}finally{f.close();}}});
test('recovered text during active response retains explicit correction/new-request choice; future requests remain distinct jobs',async()=>{const f=fixture();try{f.t.ingest([update(100,'Prima domanda'),update(101,'Seconda domanda')]);await f.t.process(at);assert.equal(jobs(f).length,2);const first=jobs(f)[0];f.s.run("UPDATE jobs SET state='running' WHERE id=?",first.id);const turn=f.s.get('telegramTurn:'+first.id);f.s.set('telegramTurn:'+first.id,{...turn,state:'running'});ignored(f,102,'Terza domanda');await f.t.process(at);assert.equal(jobs(f).length,2);assert.match(f.s.one("SELECT text FROM telegram_outbox WHERE event_id='update:102'").text,/Vuoi correggere/);const choices=f.s.all("SELECT value FROM meta WHERE key LIKE 'telegramCorrection:%'").map(r=>JSON.parse(r.value));assert.equal(choices.length,1);assert.equal(choices[0].state,'choice_pending');noEffects(f);}finally{f.close();}});
test('sent/uncertain/sending/failed delivery outcomes are preserved without job admission or automatic redelivery',async()=>{for(const outcome of ['sent','uncertain','sending','failed']){const f=fixture();try{const original=ignored(f,100,'Ci sei?');f.t.enqueue('update:100','Original reply');f.s.run('UPDATE telegram_outbox SET status=?,attempts=1 WHERE event_id=?',outcome,'update:100');const outbox=f.s.one('SELECT * FROM telegram_outbox');await f.t.process(at);await f.t.process(at);assert.equal(jobs(f).length,0);assert.deepEqual(f.s.one('SELECT * FROM telegram_outbox'),outbox);assert.deepEqual(f.s.one('SELECT * FROM telegram_updates WHERE update_id=100'),original);assert.equal(f.s.get('telegramIngressRecovery:100').outcome,'existing_delivery_retained');assert.equal(f.calls.length,0);noEffects(f);}finally{f.close();}}});
test('bounded ignored scan advances past ineligible rows while new live input is admitted first',async()=>{const f=fixture();try{for(let i=0;i<45;i++)ignored(f,100+i,'/pause');ignored(f,145,'/status');f.t.ingest([update(200,'Fresh status question',Date.parse(at)/1000)]);await f.t.process(at);assert.equal(jobs(f).length,1);assert.equal(f.s.get('telegramIngressRecoveryScan').updateId,119);assert.equal(f.s.get('telegramIngressRecovery:145'),undefined);await f.t.process(at);await f.t.process(at);assert.equal(f.s.get('telegramIngressRecovery:145').state,'done');assert.equal(jobs(f).length,1);noEffects(f);}finally{f.close();}});
for(const boundary of ['before-admission','during-admission','after-commit'] as const)test('real SIGKILL '+boundary+' preserves original update/cursor and admits one original read-only job on reopen',async()=>{const dir=mkdtempSync(join(tmpdir(),'delayed-crash-'));let f=fixture(dir,true);try{const original=ignored(f,100,'Ci sei?');f.close(false);const urls={store:new URL('../store.js',import.meta.url).href,queue:new URL('../queue.js',import.meta.url).href,control:new URL('../application-control.js',import.meta.url).href,telegram:new URL('../telegram.js',import.meta.url).href};const code=`import {Store} from ${JSON.stringify(urls.store)};import {Queue} from ${JSON.stringify(urls.queue)};import {ApplicationControl} from ${JSON.stringify(urls.control)};import {Telegram} from ${JSON.stringify(urls.telegram)};const s=new Store(${JSON.stringify(join(dir,'operational.sqlite'))}),q=new Queue(s),c=new ApplicationControl(s,q),t=new Telegram(s,c,${JSON.stringify(dir)},{call:async()=>{throw Error('No network allowed')}});const kill=()=>process.kill(process.pid,'SIGKILL');if(${JSON.stringify(boundary)}==='before-admission')c.admitWithinTransaction=kill;if(${JSON.stringify(boundary)}==='during-admission'){const set=s.set.bind(s);s.set=(key,value)=>{set(key,value);if(key==='telegramIngressRecovery:100'&&value.state==='done')kill();};}if(${JSON.stringify(boundary)}==='after-commit')t.setWake(async()=>{kill();});await t.process(${JSON.stringify(at)});throw Error('Crash boundary not reached');`;const crashed=spawnSync(process.execPath,['--input-type=module','-e',code],{encoding:'utf8',timeout:10000});assert.equal(crashed.signal,'SIGKILL',crashed.stderr);f=fixture(dir,true);assert.deepEqual(f.s.one('SELECT * FROM telegram_updates WHERE update_id=100'),original);assert.equal(f.s.get('telegramCursor'),101);assert.equal(jobs(f).length,boundary==='after-commit'?1:0);await f.t.process(at);await f.t.process(at);assert.equal(jobs(f).length,1);assert.equal(jobs(f)[0].request_id,'telegram:bot-A:100');assert.equal(jobs(f)[0].state,'queued');assert.equal(f.s.get('jobCapability:'+jobs(f)[0].id),'read_only_chat');assert.equal(f.s.one("SELECT count(*) n FROM telegram_outbox WHERE event_id='update:100'").n,1);assert.equal(f.s.get('telegramIngressRecovery:100').state,'done');assert.deepEqual(f.s.one('SELECT * FROM telegram_updates WHERE update_id=100'),original);noEffects(f);}finally{f.close();}});

test('recovery prepared before await rechecks binding/bot/original body and preserves expired receipts after authority changes',async()=>{
 for(const transition of ['pair','bot','body'] as const){const f=fixture();let release!:()=>void;try{const original=ignored(f,100,'Ci sei?'),held=new Promise<void>(r=>release=r);let entered!:()=>void;const started=new Promise<void>(r=>entered=r);Object.assign(f.t,{transport:{call:async()=>{entered();await held;return true;}}});f.t.ingest([{update_id:200,callback_query:{id:'spinner',from:{id:42},message:{chat:{id:42,type:'private'}}}}]);const processing=f.t.process(at);await started;assert.equal(f.s.get('telegramIngressRecovery:100').state,'pending');
 if(transition==='pair'){f.t.revoke();f.s.set('telegramCandidate',{userId:42,chatId:42,expires:'2026-10-10T12:20:00Z'});f.t.confirm(42,at);}else if(transition==='bot')f.s.set('telegramBotGeneration','bot-B');else {const body=JSON.parse(original.body);body.text='changed';f.s.run('UPDATE telegram_updates SET body=? WHERE update_id=100',JSON.stringify(body));}
 release();await processing;assert.equal(jobs(f).length,0);assert.equal(f.s.get('telegramIngressRecovery:100').state,'expired');assert.deepEqual(f.s.get('telegramIngressRecoveryOriginal:100'),{updateId:100,body:original.body,status:original.status,error:original.error});assert.equal(f.s.one("SELECT count(*) n FROM telegram_outbox WHERE event_id='update:100'").n,0);noEffects(f);
 }finally{release?.();f.close();}}
});
test('an existing original admission is deduplicated and mismatched capability cannot be recovered',async()=>{for(const manual of [false,true]){const f=fixture();try{const original=ignored(f,100,'Ci sei?'),job=f.c.admit('telegram:bot-A:100',manual?'proponimi una fee':'Ci sei?','telegram');f.s.set('jobTelegramGeneration:'+job.id,'binding-A');const before=f.s.one('SELECT * FROM jobs WHERE id=?',job.id);await f.t.process(at);assert.equal(jobs(f).length,1);assert.deepEqual(f.s.one('SELECT * FROM jobs WHERE id=?',job.id),before);assert.equal(f.s.get('telegramIngressRecovery:100').state,manual?'expired':'done');assert.equal(f.s.one("SELECT count(*) n FROM telegram_outbox WHERE event_id='update:100'").n,manual?0:1);assert.deepEqual(f.s.one('SELECT * FROM telegram_updates WHERE update_id=100'),original);noEffects(f);}finally{f.close();}}});

function crashBeforeRecoveryAdmission(dir:string){
 const urls={store:new URL('../store.js',import.meta.url).href,queue:new URL('../queue.js',import.meta.url).href,control:new URL('../application-control.js',import.meta.url).href,telegram:new URL('../telegram.js',import.meta.url).href};
 const code=`import {Store} from ${JSON.stringify(urls.store)};import {Queue} from ${JSON.stringify(urls.queue)};import {ApplicationControl} from ${JSON.stringify(urls.control)};import {Telegram} from ${JSON.stringify(urls.telegram)};const s=new Store(${JSON.stringify(join(dir,'operational.sqlite'))}),q=new Queue(s),c=new ApplicationControl(s,q),t=new Telegram(s,c,${JSON.stringify(dir)},{call:async()=>{throw Error('No network allowed')}});c.admitWithinTransaction=()=>process.kill(process.pid,'SIGKILL');await t.process(${JSON.stringify(at)});throw Error('Crash boundary not reached');`;
 const child=spawnSync(process.execPath,['--input-type=module','-e',code],{encoding:'utf8',timeout:10000});assert.equal(child.signal,'SIGKILL',child.stderr);
}
test('SIGKILL then public configure and same-owner confirm expires missing recovery input without repeated process errors or old admission',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'delayed-reconfigure-'));let f=fixture(dir,true);try{const original=ignored(f,100,'Ci sei?');f.close(false);crashBeforeRecoveryAdmission(dir);f=fixture(dir,true);const archive=f.s.one("SELECT value FROM meta WHERE key='telegramIngressRecoveryOriginal:100'").value,receipt=f.s.get('telegramIngressRecovery:100');assert.equal(receipt.state,'pending');assert.equal(jobs(f).length,0);
 f.t.configure('123456789:abcdefghijklmnopqrstuvwxyzABCDE');assert.equal(f.s.one('SELECT * FROM telegram_updates WHERE update_id=100'),undefined);const pairing=f.t.pairing(at);f.t.ingest([update(1,'/start '+pairing.code,Date.parse(at)/1000)]);await f.t.process(at);f.t.confirm(42,at);const newBot=f.s.get('telegramBotGeneration');assert.notEqual(newBot,'bot-A');f.t.ingest([update(2,'/status',Date.parse(at)/1000)]);await assert.doesNotReject(f.t.process(at));f.t.ingest([update(3,'Ci sei?',Date.parse(at)/1000)]);await assert.doesNotReject(f.t.process(at));
 const expired=f.s.get('telegramIngressRecovery:100');assert.equal(expired.state,'expired');assert.equal(expired.outcome,'original_receipt_unavailable_or_changed');for(const key of ['requestId','eventId','bodyHash','generation','botGeneration','chatId','at'])assert.deepEqual(expired[key],receipt[key]);assert.equal(f.s.one("SELECT value FROM meta WHERE key='telegramIngressRecoveryOriginal:100'").value,archive);assert.equal(JSON.parse(archive).body,original.body);assert.equal(jobs(f).length,1);assert.equal(jobs(f)[0].request_id,'telegram:'+newBot+':3');assert.equal(f.s.get('jobCapability:'+jobs(f)[0].id),'read_only_chat');assert.equal(f.s.one("SELECT count(*) n FROM telegram_outbox WHERE event_id='update:100'").n,0);assert.equal(f.s.one("SELECT status FROM telegram_outbox WHERE event_id='update:2'").status,'pending');noEffects(f);
 }finally{f.close();}
});
test('changed or invalid original pending recovery expires before parsing and leaves archived identity intact',async()=>{
 for(const changed of ['body','invalid-json','status'] as const){const dir=mkdtempSync(join(tmpdir(),'delayed-invalid-original-'));let f=fixture(dir,true);try{ignored(f,100,'Ci sei?');f.close(false);crashBeforeRecoveryAdmission(dir);f=fixture(dir,true);const archive=f.s.one("SELECT value FROM meta WHERE key='telegramIngressRecoveryOriginal:100'").value,receipt=f.s.get('telegramIngressRecovery:100');if(changed==='status')f.s.run("UPDATE telegram_updates SET status='done' WHERE update_id=100");else f.s.run('UPDATE telegram_updates SET body=? WHERE update_id=100',changed==='invalid-json'?'{invalid':JSON.stringify({text:'changed'}));await assert.doesNotReject(f.t.process(at));await assert.doesNotReject(f.t.process(at));assert.equal(f.s.get('telegramIngressRecovery:100').state,'expired');assert.equal(f.s.get('telegramIngressRecovery:100').requestId,receipt.requestId);assert.equal(f.s.get('telegramIngressRecovery:100').bodyHash,receipt.bodyHash);assert.equal(f.s.one("SELECT value FROM meta WHERE key='telegramIngressRecoveryOriginal:100'").value,archive);assert.equal(jobs(f).length,0);assert.equal(f.s.all('SELECT * FROM telegram_outbox').length,0);noEffects(f);}finally{f.close();}}
});
test('invalid ignored source bodies are skipped per row so valid live and later recovery inputs retain their normal handling',async()=>{const f=fixture();try{for(const [i,body] of ['{invalid','null','[]'].entries())f.s.run("INSERT INTO telegram_updates(update_id,body,status,error) VALUES(?,?,'ignored','Stale incoming command')",100+i,body);ignored(f,103,'/status');f.t.ingest([update(200,'Ci sei?',Date.parse(at)/1000)]);await assert.doesNotReject(f.t.process(at));await assert.doesNotReject(f.t.process(at));assert.equal(jobs(f).length,1);assert.equal(jobs(f)[0].request_id,'telegram:bot-A:200');assert.equal(f.s.get('telegramIngressRecovery:103').state,'done');assert.equal(f.s.get('telegramIngressRecovery:100'),undefined);noEffects(f);}finally{f.close();}});
