version: "3.7"

services:
  app_proxy:
    container_name: whirmill-datum-core_app_proxy_1
    environment:
      APP_HOST: whirmill-datum-core_datum_1
      APP_PORT: 21000

  datum:
    container_name: whirmill-datum-core_datum_1
    image: ghcr.io/retropex/datum:v1.14@sha256:c67ac8afb4f90f6f8090b8130ab834b20177efb2246895084525a15078cedc47
    entrypoint: ["/app/datum_gateway"]
    command: ["--config=/app/conf/datum_gateway_config.json"]
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 30s
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ${APP_DATA_DIR}/data/settings:/app/conf
    ports:
      - "23334:23334"
    security_opt:
      - no-new-privileges:true
