version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: whirmill-byparr_server_1
      APP_PORT: 8191

  server:
    image: ghcr.io/thephaseless/byparr:3.0.4@sha256:874f719518f617d03a60e03411fc5d090647e1a877041e81f8dc965927c7deb6
    restart: on-failure
    init: true
    environment:
      HOST: 0.0.0.0
      PORT: "8191"
    shm_size: 512mb
    security_opt:
      - no-new-privileges:true
    pids_limit: 512
    mem_limit: 2g
    stop_grace_period: 30s
